### ISSUE TITLE
createStandardMenuItem()'s onExecute is required for the content to be visible

### ISSUE THREAD

**Issue by sancarn** [LaunchMenu/LaunchMenu#141]
**Describe the bug**
The following applet will not display content as the item will not be selectable:

```ts
export default declare({
    info,
    settings,
    async search(query, hook) {
      return {
        item: {
          priority: Priority.EXTRAHIGH,
          item: createStandardMenuItem({
            name: h => result.get(h),
            content: <span>yop</span>
          }),
        },
      };
    },
});
```

However this applet will:

```ts
export default declare({
    info,
    settings,
    async search(query, hook) {
      return {
        item: {
          priority: Priority.EXTRAHIGH,
          item: createStandardMenuItem({
            name: h => result.get(h),
            content: <span>yop</span>,
            onExecute: () => {},
          }),
        },
      };
    },
});
```

From this we can infer that onExecute is required in order to display content.
I believe we initially justified this instead of having a "selectable" flag. Perhaps if content is provided `onExecute` should default to `()=>{}`?

**Comment by TarVK** [comment]
This is in my opinion not a bug. It's intentional design (I don't know whether I documented it properly anywhere, but there's a reference to it here: https://launchmenu.github.io/docs/concepts/ui/menu#advanced-categories). I however agree this isn't fully intuitive, and may be improved upon.

The idea of having a default onExecute when content is provided may be problematic however, since this will force the context menu item of the execute action to be the most generic item. So it prevents specialization of the execute context menu item when an item with essentially no execution is present in the selection. 

Of course this is an acceptable minor inconvenience, but I've an idea for a potentially better approach:
We can introduce a `isSelectable` action, and simply make both the execute action and the content action create a binding to this when present. That way both content and execute bindings will make sure the item is selectable. In addition we could then add behavior such that when the following binding is present: `isSelectable.createBinding(false)`, it will force the item not to be selectable even though it has e.g. an execute binding.
